Как видите, данной системой достаточно просто пользоваться. Но "Hello World" - это слишком просто. Давайте познакомимся с чем-то, что Вы будете использовать в дальнейшем. Начнём с NumPy - полезной библитекой для работы с многомерными массивами (в том числе и матрицами) в Python. Если Вы программируете на Python и обрабатываете массивы, обязательно посмотрите на возможности этой библиотеки. Во-первых, она позволяет очень просто выполнять операции на массивах и матрицах. Во-вторых, она делает это быстро (потому что содержит оптимизированный код на C). Если думаете написать какую-то обработку массивов и матриц, поищите, нет ли подходящей функции в NumPy. В общем, рекомендую посмотреть документацию этой библиотеки.

Импортировать NumPy можно следующим образом (выполните один раз):

In [1]:
import numpy

Также часто на практике пишут ```import numpy as np```, чтобы меньше писать.



Задача 0.b "Hello NumPy". Необходимо реализовать функцию, которая принимает на входе один аргумент - матрицу (двухмерный массив NumPy) с числами типа float. Функция должна вернуть одномерный массив NumPy с числами типа float, в котором содержатся минимальные/максимальные/средние (в зависимости от варианта) значения чисел в столбцых матрицы (количество элементов массива на входе должно равняться количеству столбцов матрицы на входе). Варианты:
0. минимальное
1. максимальное
2. среднее

Будьте внимательны, во входных матрицах могут содержаться _необычные_ числа.

Пример: 1 вариант, входная матрица: $$\begin{bmatrix} 1 & 6 & 7 \\ 2 & 5 & 8 \\ 3 & 4 & 9\end{bmatrix},$$ массив на выходе: $$\begin{bmatrix} 3 & 6 & 9\end{bmatrix}.$$


Для начала выполните следующий вспомогательный код один раз

In [2]:
import urllib.request
from json import dumps, loads

server = "https://eztester.agridnev.com"
task_id = 2

def get_variant():
  response = urllib.request.urlopen(server + "/task/" + str(task_id) + "/variant?secret=" + secret)
  variant = int(response.read().decode("utf-8"))
  return variant

def auto_test(func):
  response = urllib.request.urlopen(server + "/task/" + str(task_id) + "?secret=" + secret)
  token = response.read().decode("utf-8")
  results = []
  for case in range(7):
    response = urllib.request.urlopen(server + "/data/matrix?case=" + str(case) + "&token=" + token)
    matrix = numpy.array(loads(response.read().decode("utf-8")), dtype=float)
    print("Matrix:", matrix)
    result = func(matrix)
    print("Result:", result)
    results.append(result.tolist())
  req = urllib.request.Request(server + "/solution?token=" + token)
  req.add_header("Content-Type", "application/json")
  data = dumps(results).encode('utf-8')
  req.add_header('Content-Length', len(data))
  response = urllib.request.urlopen(req, data)
  print("Passed! First time passed:", response.read().decode("utf-8"))

def print_info():
  response = urllib.request.urlopen(server + "/user?secret=" + secret)
  info = loads(response.read().decode("utf-8"))
  print("Full name:", info["name"])
  print("Group:", info["group"])
  print("Tasks: (id --- name --- solution)")
  for id in info["tasks"]:
    task = info["tasks"][id]
    print(id, "---", task["name"], "---", task["solution"])

Далее введите свой секрет (Вы уже должны были использовать его в предыдущей части лабораторной работы). Держите секрет в секрете!

In [3]:
secret = "faaf64fa1f4b461fa2d627ffaec3ce4a"

Теперь выполните этот код для получения варианта

In [4]:
get_variant()

2

Теперь ниже реализуйте функцию, которая требудется по условию задания

In [29]:
def your_function(matrix):
  result = matrix.mean(0)
  return result

Теперь самостоятельно проверьте, как она работает

In [30]:
for matrix in [numpy.array([[1., 2.], [3., 4.]]), numpy.array([[1., 6., 7.], [2., 5., 8.], [3., 4., 9.]])]:
  print("Matrix:", "(shape", matrix.shape, ")")
  print(matrix)
  result = your_function(matrix)
  print("Result:", result, "(shape", result.shape, ")")

Matrix: (shape (2, 2) )
[[1. 2.]
 [3. 4.]]
Result: [2. 3.] (shape (2,) )
Matrix: (shape (3, 3) )
[[1. 6. 7.]
 [2. 5. 8.]
 [3. 4. 9.]]
Result: [2. 5. 8.] (shape (3,) )


Если всё хорошо, настало время автоматической проверки

In [31]:
auto_test(your_function)

Matrix: [[0.59123093]]
Result: [0.59123093]
Matrix: [[0.93265952 0.64490507]]
Result: [0.93265952 0.64490507]
Matrix: [[0.60676085]
 [0.58767689]]
Result: [0.59721887]
Matrix: [[0.62589049 0.7686421 ]
 [0.39242897 0.43796831]]
Result: [0.50915973 0.60330521]
Matrix: [[ -44.72538404  321.56278839   76.6940913  -255.37593859  430.43120309
   389.22808885 -231.02842684  477.08802108 -421.79769013 -126.74673324
  -223.18362873]
 [-272.53536752  105.44263203  442.92714266   -8.28458544   75.13667348
   378.87455071   49.37141503 -205.44876929  331.60980643  347.34265712
  -173.10127069]
 [-172.71868891  -86.63572403 -388.91884005  -63.95238815    6.2619355
   475.72565499  147.26484904  -19.02611288   96.63507727  -39.62307294
  -216.26913231]
 [ 435.06173091 -105.77264132 -147.17774014 -155.65014892  161.96552581
   -99.12741816 -148.11643557 -426.57907733  400.51720353  392.07235293
  -278.67935135]
 [ -34.67536481   -6.43982477   81.31830544  107.93849333 -141.19313308
  -225.25066058   

Как и в прошлый раз, если Вы увидели "Passed!", значит всё ОК, скидывайте решение в расшаренную преподавателю папку на Google Drive.

Если же Вы увидели какую-то ошибку, что-то пошло не так. Возможные причины:
* код 408 - между полученим данных и отправкой результатов прошло слишком много времени (для этой задачи стоит ограничение в 5 секунд на все 7 теста вместе)
* код 418 - неверное решение (что именно в нём неправильно - система не скажет)

Также Вы можете посмотреть информацию о себе в системе (ФИО, группу, список доступных заданий и результаты их выполнения):

In [ ]:
print_info()